### PR TITLE
"Unauthorized use of Copyrighted Content" fixed

### PR DESCRIPTION
**Pull request by TheAlienDrew**
Though, keep in mind this is a temporary work around, and therefore Musescore might break it instantly when they get the chance to.

### CODE REVIEW

**Comment by TheAlienDrew** [comment]
And it's up to you, but I also put in an `alert` to warn users of the script of this 8 seconds timeout work around, but there's probably better ways to display that message... maybe a countdown somewhere in the script.

**Comment by TheRaphael0000** [comment]
I think you've changed the line break character in your commit

**Comment by TheAlienDrew** [comment]
Well I did do it through GitHub online... and it did say it was going to change it to windows line breaks, I can go ahead and change it to unix line breaks though if that's preferred.

**Comment by TheRaphael0000** [comment]
It's not my repository, so I don't really know if @Xmader care. But yeah I think it's better to only have the actual change in your commit to be able to see what you did.

**Comment by TheAlienDrew** [comment]
Here we go, I made a new one with the fixed line breaks: https://github.com/Xmader/musescore-downloader/pull/50

**Comment by TheRaphael0000** [comment]
Thank you !

**Pull request closed without merging**
