### PR TITLE
Fix discord url #68

### PR DESCRIPTION
**Pull request by guysoft**
The current discord url is broken, this fixes it.

Related  #68 #141

### CODE REVIEW

**Comment by SealsRock12** [comment]
This repo is not being used anymore, the new one is at https://github.com/LibreScore/dl-musescore

**Comment by Kenora-I** [comment]
Fixed.

**Comment by Andreu67** [comment]
fix it again pls
@guysoft

**Comment by guysoft** [comment]
@Andreu67 I am not part of this project. And my PR was not merged.

**Comment by Andreu67** [comment]
@guysoft But can you still give me an invite link?

**Comment by guysoft** [comment]
Its in the "files changed" tab dude:
https://discord.gg/kTyx6nUjMv
If it does not work it changed again and I dont know it

**Comment by Andreu67** [comment]
> Its in the "files changed" tab dude: https://discord.gg/kTyx6nUjMv If it does not work it changed again and I dont know it
It still didn't work but thanks
:) :D

**Comment by Andreu67** [comment]
I didn't work but still thanks
:)

**Pull request closed without merging**
